import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import QueryClientProvider from "@/providers/QueryClientProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <QueryClientProvider>
          <ReactQueryDevtools initialIsOpen={false} />
            
      <Layout>

            {children}
      </Layout>
</QueryClientProvider>

      </body>
    </html>
  );
}
